name: CI
on: [push]
jobs:
    phpcs:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/phpcs

    phpstan:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpstan

    phpdd:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpdd

    composer-require-checker:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/composer-require-checker

    composer-validate:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/composer-validate

    phpunit-php-7-4-symfony-5-0:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-7-4-symfony-5-0

    phpunit-php-7-4-symfony-5-1:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-7-4-symfony-5-1

    phpunit-php-7-4-symfony-5-2:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-7-4-symfony-5-2

    phpunit-php-7-4-symfony-5-3:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-7-4-symfony-5-3

    phpunit-php-8-0-symfony-5-0:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-8-0-symfony-5-0

    phpunit-php-8-0-symfony-5-1:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-8-0-symfony-5-1

    phpunit-php-8-0-symfony-5-2:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-8-0-symfony-5-2

    phpunit-php-8-0-symfony-5-3:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/ci/env
            - run: bin/ci/phpunit-php-8-0-symfony-5-3

    shellcheck:
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/shellcheck
