name: "Prepare release"

on:
    workflow_dispatch:
        inputs:
            version:
                description: Version
                required: true

jobs:
    build:
        name: Prepare release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/release/prepare "${{ github.event.inputs.version }}"
            -
                name: Create PR
                uses: peter-evans/create-pull-request@v3
                with:
                    title: Prepare release ${{ github.event.inputs.version }}
                    commit-message: Prepare release ${{ github.event.inputs.version }}
                    branch: release-foo
                    delete-branch: true
                    body: ''
