name: "Prepare release"

on:
    workflow_dispatch:
        inputs:
            version:
                description: Version
                required: true

jobs:
    build:
        name: Prepare release
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:ci
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/prepare-release "${{ github.event.inputs.version }}"
