name: "Release"

on:
    push:
        tags:
            - "*"

jobs:
    build:
        name: Create release
        runs-on: ubuntu-latest
        container:
            image: steevanb/php-parallel-process:release
        steps:
            - uses: actions/checkout@v2
            -
                name: Composer cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.json') }}
                    restore-keys: composer-${{ hashFiles('composer.json') }}
            - run: bin/release/env
            -
                name: Create release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: ${{ github.ref }}
                    body: "[Changelog](changelog.md)"
